name: Deploy Demo

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn && yarn build:demo
      - name: Deploy to ByteInspire Hosting
        id: byteinspire_hosting_deployer
        uses: byteinspire/hosting-deployer-action@v1
        with:
          service-id: "${{ secrets.SERVICE_ID }}"
          token: "${{ secrets.ACCESS_TOKEN }}"
          directory: "./demo_dist"
          changelog: "deploy by action"
